# Generated by Django 3.2.4 on 2021-08-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('idanswer', models.BigAutoField(db_column='idAnswer', primary_key=True, serialize=False)),
                ('comentanswer', models.CharField(db_column='comentAnswer', max_length=8192)),
                ('stateanswer', models.BigIntegerField(blank=True, db_column='stateAnswer', null=True)),
                ('datecreationanswer', models.DateTimeField(db_column='dateCreationAnswer')),
                ('iduser', models.BigIntegerField(db_column='idUser')),
            ],
            options={
                'db_table': 'Answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idcomment', models.BigAutoField(db_column='idComment', primary_key=True, serialize=False)),
                ('datecreationcomment', models.DateTimeField(db_column='dateCreationComment')),
                ('contentcomment', models.CharField(db_column='contentComment', max_length=8192)),
                ('statecomment', models.BigIntegerField(blank=True, db_column='stateComment', null=True)),
            ],
            options={
                'db_table': 'Comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('worddictionary', models.CharField(db_column='wordDictionary', max_length=128)),
                ('audiodictionary', models.BinaryField(blank=True, db_column='audioDictionary', null=True)),
                ('iddictionary', models.BigAutoField(db_column='idDictionary', primary_key=True, serialize=False)),
                ('traslatedictionary', models.CharField(db_column='traslateDictionary', max_length=128)),
                ('pronunciationdictionary', models.CharField(db_column='pronunciationDictionary', max_length=128)),
                ('descriptiondictionary', models.CharField(db_column='descriptionDictionary', max_length=256)),
                ('resourcedictionary', models.CharField(blank=True, db_column='resourceDictionary', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Dictionary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examplesdictionay',
            fields=[
                ('idexamplesdictionay', models.BigIntegerField(db_column='idExamplesDictionay', primary_key=True, serialize=False)),
                ('sentencesexamplesdictionay', models.TextField(db_column='sentencesExamplesDictionay')),
            ],
            options={
                'db_table': 'ExamplesDictionay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('idgroup', models.BigAutoField(db_column='idGroup', primary_key=True, serialize=False)),
                ('imagecovergroup', models.BinaryField(blank=True, db_column='imageCoverGroup', null=True)),
                ('namegroup', models.CharField(db_column='nameGroup', max_length=128)),
                ('descriptiongroup', models.CharField(db_column='descriptionGroup', max_length=256)),
                ('datecreationgroup', models.DateTimeField(db_column='dateCreationGroup')),
                ('stategroup', models.IntegerField(blank=True, db_column='stateGroup', null=True)),
                ('typegroup', models.IntegerField(blank=True, db_column='typeGroup', null=True)),
            ],
            options={
                'db_table': 'Group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('idhistory', models.BigAutoField(db_column='idHistory', primary_key=True, serialize=False)),
                ('datemodificationhistory', models.DateTimeField(db_column='dateModificationHistory')),
                ('contentstringhistory', models.TextField(db_column='contentStringHistory')),
            ],
            options={
                'db_table': 'History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('questionpreference', models.CharField(db_column='questionPreference', max_length=256)),
                ('answerpreference', models.CharField(blank=True, db_column='answerPreference', max_length=128, null=True)),
                ('idpreference', models.BigAutoField(db_column='idPreference', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Preference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Readinglist',
            fields=[
                ('iduser', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('datecreationreadinglist', models.BigIntegerField(db_column='dateCreationReadingList')),
                ('namereadinglist', models.BigIntegerField(db_column='nameReadingList')),
            ],
            options={
                'db_table': 'ReadingList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('idstory', models.BigAutoField(db_column='idStory', primary_key=True, serialize=False)),
                ('titlestory', models.CharField(db_column='titleStory', max_length=128)),
                ('descriptionstory', models.CharField(db_column='descriptionStory', max_length=2048)),
                ('imagecoverstory', models.BinaryField(blank=True, db_column='imageCoverStory', null=True)),
                ('likesstory', models.IntegerField(blank=True, db_column='likesStory', null=True)),
                ('contentstringstory', models.TextField(db_column='contentStringStory')),
                ('datecreationstory', models.DateTimeField(db_column='dateCreationStory')),
                ('statestory', models.IntegerField(blank=True, db_column='stateStory', null=True)),
            ],
            options={
                'db_table': 'Story',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('idsuggestion', models.BigAutoField(db_column='idSuggestion', primary_key=True, serialize=False)),
                ('suggestion', models.TextField(blank=True, db_column='Suggestion', null=True)),
            ],
            options={
                'db_table': 'Suggestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('iduser', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user')),
                ('staterequestusergroup', models.IntegerField(db_column='stateRequestUserGroup')),
                ('rolusergroup', models.IntegerField(db_column='rolUserGroup')),
                ('dateusergroup', models.DateTimeField(blank=True, db_column='dateUserGroup', null=True)),
            ],
            options={
                'db_table': 'UserGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('emailuser', models.CharField(db_column='emailUser', max_length=512)),
                ('passworduser', models.CharField(db_column='passwordUser', max_length=64)),
                ('firstnameuser', models.CharField(db_column='firstnameUser', max_length=128)),
                ('lastnameuser', models.CharField(blank=True, db_column='lastnameUser', max_length=128, null=True)),
                ('imagecoveruser', models.BinaryField(blank=True, db_column='imageCoverUser', null=True)),
                ('countryuser', models.CharField(blank=True, db_column='countryUser', max_length=512, null=True)),
                ('phoneuser', models.IntegerField(blank=True, db_column='phoneUser', null=True)),
                ('usernameuser', models.CharField(db_column='usernameUser', max_length=128)),
                ('adressuser', models.CharField(blank=True, db_column='adressUser', max_length=512, null=True)),
                ('cityuser', models.CharField(blank=True, db_column='cityUser', max_length=512, null=True)),
                ('stateuser', models.IntegerField(blank=True, db_column='stateUser', null=True)),
                ('datecreationuser', models.DateTimeField(db_column='dateCreationUser')),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
