# Generated by Django 3.2.4 on 2021-09-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('DivertiCuentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='auth.user')),
                ('email', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(blank=True, max_length=128, null=True)),
                ('imagecover', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=128)),
                ('adress', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=512, null=True)),
                ('state', models.IntegerField(blank=True, default=1, null=True)),
                ('datecreation', models.DateTimeField()),
            ],
        ),
    ]
