# Generated by Django 3.2.4 on 2021-09-02 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DivertiCuentos', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('iduser', models.BigAutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='emailUser', max_length=512)),
                ('password', models.CharField(db_column='passwordUser', max_length=64)),
                ('firstname', models.CharField(db_column='firstnameUser', max_length=128)),
                ('lastname', models.CharField(blank=True, db_column='lastnameUser', max_length=128, null=True)),
                ('imagecover', models.ImageField(blank=True, db_column='imageCoverUser', null=True, upload_to='image/')),
                ('country', models.CharField(blank=True, db_column='countryUser', max_length=512, null=True)),
                ('phone', models.IntegerField(blank=True, db_column='phoneUser', null=True)),
                ('username', models.CharField(db_column='usernameUser', max_length=128)),
                ('adress', models.CharField(blank=True, db_column='adressUser', max_length=512, null=True)),
                ('city', models.CharField(blank=True, db_column='cityUser', max_length=512, null=True)),
                ('state', models.IntegerField(blank=True, db_column='stateUser', default=1, null=True)),
                ('datecreation', models.DateTimeField(db_column='dateCreationUser')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserP',
        ),
    ]
