# Generated by Django 3.2.4 on 2021-09-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DivertiCuentos', '0003_auto_20210902_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
